
spring:
  application:
    name: msteacher

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://some-postgres:5432/professor_db
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
          format_sql: true
          show_sql: true


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
