
spring:
  application:
    name: msaddress

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-address-db:5432/address_db
    username: postgres
    password: zxcvbnm123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
