
spring:
  application:
    name: msuser
  profiles:
    active: local #configuração local. Para rodar no docker é necessario retirar essa config

  #Definindo tamanho maximo de arquivo recebido
  #servlet:
   # multipart:
    #  max-file-size: 500KB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-user-db:5432/user_db
    username: postgres
    password: zxcvbnm123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
